import Head from 'next/head'
import {Badge, Button, Container, Typography} from "@mui/material";
import {useState} from "react";

export default function Home() {
    const [counter, setCounter] = useState(0)
    return <>
        <Head>
            <title>Next MUI App</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <Container component="main">
            <Typography variant="h1">
                Next + MUI
            </Typography>
            <Badge badgeContent={counter} color="secondary">
                <Button
                    variant="contained"
                    onClick={() => {
                        setCounter(counter + 1)
                    }}
                >
                    点我
                </Button>
            </Badge>
        </Container>
    </>
}
